[package]
name = "term_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
serde = { version = "1.0.214", features = ["derive"] }
terminal_size = "0.3.0"

[profile.profiling]
inherits = "release"
debug = true
